apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockchain
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: blockchain
    fsType: ext4
